tls_server_config:
  cert_file: "/etc/kubernetes/certs/kubeletserver.crt"
  key_file: "/etc/kubernetes/certs/kubeletserver.key"
  client_auth_type: "RequireAndVerifyClientCert"
  client_ca_file: "/etc/kubernetes/certs/ca.crt"
